#!/usr/bin/env python3
import libaur.aur as libaur
import libaur.printer
import libaur.errors as error
import libaur
import configparser
import xdg.BaseDirectory
import argparse
import re
from os import path

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            description='A simple AUR helper in python.',
            epilog='See the config file in $PREFIX/share/doc/pywer. \
                   Copy it to {} and edit it for use, or use `--config`.\
                   You may need to update the config file when updating\
                   pywer.'\
                   .format(xdg.BaseDirectory.xdg_config_home),
                   )
    # Operations
    # TODO: Find some way to only allow a single operation
    operations = parser.add_argument_group('Operations')
    operations.add_argument('-s', '--search',
                        help='Search for this package',
                        metavar='term')
    operations.add_argument('-i', '--info',
                        help='Get info for this package',
                        metavar='pkg', nargs='+')
    operations.add_argument('-m', '--msearch',
                        help='Search for this maintainers packages',
                        metavar='maintainer')
    operations.add_argument('-u', '--update',
                        help='Print package updates for the system',
                        metavar='pkg', nargs='*', default='-DEFAULT')
    operations.add_argument('-d', '--download',
                        help='Download the package',
                        metavar='pkg', nargs='+')

    # Options
    options = parser.add_argument_group('Options')
    options.add_argument('-q', '--quiet',
                        help='Be quieter',
                        action='count', default=0)
    options.add_argument('-v', '--verbose',
                        help='Be verbose',
                        action='count', default=0)
    options.add_argument('-f', '--force',
                        help='overwrite existing files while downloading',
                        action='store_true')
    options.add_argument('--config',
                        help='Specify an alternate config',
                        metavar='file')
    options.add_argument('-V', '--version',
                        help='Print version',
                        action='version', version='%(prog)s {}'.format(libaur.__version__))
    options.add_argument('-o', '--ignore-ood',
                        help='Ignore out of date packages',
                        action='store_true')
    options.add_argument('--no-ignore-ood',
                        help='Do not ignore out of date packages',
                        action='store_true')
    options.add_argument('-c', '--color',
                        help='Use color',
                        action='store_true')
    options.add_argument('--no-color',
                        help='Do not use color',
                        action='store_true')
    config_opts = parser.add_argument_group('Configuration Options')
    config_opts.add_argument('--ignorerepo',
                        help='Specify comma separated list of repos to ignore',
                        metavar='repo')
    config_opts.add_argument('-t', '--target',
                        help='Specify an alternate download location',
                        metavar='dir')
    config_opts.add_argument('--baseurl',
                        help='Set a custom baseurl to an AUR',
                        metavar='url')
    args = parser.parse_args()

    config = configparser.ConfigParser()
    if args.config:
        use_config = args.config
    else:
        use_config = xdg.BaseDirectory.xdg_config_home + '/pywer/pywer.ini'
    config.read(use_config)

    if libaur.__version__ > config['PYWER']['CONFIGVER']:
        raise error.ConfigWrongVersion('''Your pywer config is for an older
        version of pywer. Please see the file in $PREFIX/share/doc/pywer.''')


    if not path.exists(use_config):
        message = 'pywer requires a config file at {}. See `pywer -h`.'\
                .format(use_config)
        raise error.ConfigMissing(message)

    SHOW_OOD=True
    if args.ignore_ood or config['Repos']['IgnoreOOD'] == 'yes':
        SHOW_OOD=False
    if args.no_ignore_ood:
        SHOW_OOD=True

    if args.color:
        USE_COLOR = True
    elif args.no_color:
        USE_COLOR = False
    elif config['Repos']['Color'] == 'yes':
        USE_COLOR = True
    else:
        USE_COLOR = False

    VERBOSE = args.verbose - args.quiet

    FORCE=False
    if args.force:
        FORCE=True

    if args.baseurl:
        _baseurl = args.baseurl
    else:
        _baseurl = config['AUR']['BaseUrl']

    if args.search:
        libaur.printer.pretty_print_search(args.search, baseurl=_baseurl,
                ood=SHOW_OOD, be_verbose=VERBOSE, color=USE_COLOR)
    elif args.msearch:
        libaur.printer.pretty_print_search(args.msearch, stype='msearch',
                baseurl=_baseurl, ood=SHOW_OOD, be_verbose=VERBOSE,
                color=USE_COLOR)
    elif args.info:
        libaur.printer.pretty_print_simple_info(args.info, baseurl=_baseurl,
                ood=SHOW_OOD, color=USE_COLOR)
    elif args.download:
        if args.target:
            dl_path = path.expanduser(args.target)
        else:
            dl_path = path.expanduser(config['Filesystem']['DownloadPath'])
        dl_path = path.expandvars(dl_path)
        libaur.printer.download_pkgs(args.download, dl_path, dl_verbose=VERBOSE,
                baseurl=_baseurl, dl_force=FORCE, ood=SHOW_OOD, color=USE_COLOR)
    elif not args.update == '-DEFAULT':
        if args.ignorerepo:
            libaur.printer.pretty_print_updpkgs(other_repos=[args.ignorerepo],
                    baseurl=_baseurl, pkgs=args.update, be_verbose=VERBOSE,
                    color=USE_COLOR)
        else:
            _or = re.split(',', config['Repos']['IgnoreRepo'])
            libaur.printer.pretty_print_updpkgs(other_repos=_or,
                    baseurl=_baseurl, pkgs=args.update, be_verbose=VERBOSE,
                    color=USE_COLOR)
    else:
        print('error: No operation specified. (use -h for help)')
